# Site settings
#title: "Bitácora de Factores"
title: "Factores"
#email: info@factores.es
lema: 2. m. y f. p. us. Persona que hace algo.
description: "Ingeniero Técnico de Telecomunicaciones Graduado en Ingeniería Mecáncia"
baseurl: ""
url: ""
twitter_username: factores_es
github_username:  factores
# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
#redcarpet
#kramdown
#permalink: pretty
