# Site settings
#title: "Bitácora de Factores"
title: "Factores"
#email: info@factores.es
lema: La libertad es hacer y se aprende haciendo
description: "Ingeniero Técnico de Telecomunicaciones y Graduado en Ingeniería Mecáncia"
baseurl: ""
url: ""
twitter_username: factores_es
github_username:  factores
# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
#redcarpet
#kramdown
#permalink: pretty
